---
title: "Enhancing Chemotherapy Response Prediction via Matched Colorectal Tumor-Organoid Gene Expression Analysis and Network-Based Biomarker Selection"
subtitle: "GSE17538"
author: "Wei Zhang, Hanchen Huang, Xi S.Chen"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
    highlight: pygments
    theme: yeti
    toc: true
    number_sections: true
    df_print: paged
    code_download: false
    toc_float:
      collapsed: yes
    toc_depth: 3
editor_options:
  chunk_output_type: inline    
---

```{r setup, include=FALSE}
# Initial settings
knitr::opts_chunk$set(echo = TRUE)

dir.base <- "../../../"
# Create and retrieve dir
GEO <- "GSE17538"
dir.data <- file.path(dir.base, "data/", GEO)
dir.data.raw <- file.path(dir.data, "raw")
dir.data.processed <- file.path(dir.data, "processed")
dir.data.clinical <- file.path(dir.data, "clinical")

# Create results dir
dir.results <- file.path(dir.base, "analysis-results/")
for(p in grep("dir",ls(),value = T)) dir.create(get(p),recursive = TRUE,showWarnings = FALSE)
```

# Auxillary function

```{r message = F}
fn_ls <- list.files("../utility/", pattern = ".R", full.names = T)
for (f in fn_ls) source(f)
```

# Data preprocessing

## Data download and get expression data

```{r eval = F}
# Gene expression profile of colorectal cancer tissues from 87 patients
GSE17538 <- getGEO(GEO = "GSE17538", destdir = dir.data.raw)
```

```{r}
# Get phenotype
pheno_GSE17538 <- pData(GSE17538$`GSE17538-GPL570_series_matrix.txt.gz`) %>%
  clean_names()

write_csv(
  pheno_GSE17538,
  file.path(dir.data.clinical, "GSE17538_clinical_data.csv")
)
```

```{r}
# fMRA normalization
exp <- exprs(GSE17538$`GSE17538-GPL570_series_matrix.txt.gz`)

#### use probe with largest IDR to represent the gene
arrayIQR <- apply(exp,1,IQR)
probe <- rownames(exp)
uniqueGenes <- findLargest(as.vector(probe),arrayIQR,'hgu133plus2')

# Add gene symbol
exp2 <- exp[uniqueGenes,]
gene_symbol <- AnnotationDbi::select(hgu133plus2.db, 
                      keys = uniqueGenes, 
                      columns ="SYMBOL")
rownames(exp2) <- gene_symbol$SYMBOL

# Save raw expression data
write_csv(
  exp2 %>% data.frame() %>% rownames_to_column("Gene"),
  file.path(dir.data.processed, paste0(GEO, "_raw_exp_data.csv"))
)
```

## Preprocessing clinical data

```{r}
clinical <- pheno_GSE17538[,c(1:2,45:56)]

# remove samples with NA in dfs
clinical <- clinical %>%
  filter(!is.na(dfs_event_disease_free_survival_cancer_recurrence_ch1)) %>%
  mutate(rfs = ifelse(dfs_event_disease_free_survival_cancer_recurrence_ch1 == "NA", NA,
                      ifelse(dfs_event_disease_free_survival_cancer_recurrence_ch1 == "no recurrence", 0, 1)),
         dss = ifelse(dss_event_disease_specific_survival_death_from_cancer_ch1 == "no death", 0, 1),
         os = ifelse(overall_event_death_from_any_cause_ch1 == "no death", 0, 1),
         os_month = as.numeric(overall_survival_follow_up_time_ch1),
         dss_month = as.numeric(dss_time_ch1),
         rfs_month = as.numeric(dfs_time_ch1))

write_csv(
  clinical,
  file.path(dir.data.clinical, "GSE17538_clinical_with_rfs.csv")
)
```

## Match with expression data

```{r}
exp2 <- exp2[,clinical$geo_accession]

write_csv(
  exp2 %>% data.frame() %>% rownames_to_column("Gene"),
  file.path(dir.data.processed, paste0(GEO, "_rfs_exp_data.csv"))
)
```

```{r}
save(
  exp2,
  clinical,
  file = file.path(dir.data.processed, "GSE17538_with_rfs_exp_clinical_data.rda")
)
```

# Read additional drug information

```{r}
load(file.path(dir.data.processed, "GSE17538_with_rfs_exp_clinical_data.rda"))
drug_info <- read.delim(
  file.path(dir.data.raw, "GSE17536clinical.txt")
) %>% data.frame() %>% 
  dplyr::select(
  geoid, AdjCTX
) %>% mutate(geo_accession = geoid, .keep = "unused")
```

```{r}
clinical <- left_join(clinical, drug_info)
```

```{r}
save(
  exp2,
  clinical,
  file = file.path(dir.data.processed, "GSE17538_with_rfs_exp_clinical_data.rda")
)
```

# Session Information

```{r}
devtools::session_info()
```

