---
title: "Enhancing Chemotherapy Response Prediction via Matched Colorectal Tumor-Organoid Gene Expression Analysis and Network-Based Biomarker Selection"
subtitle: "Organoids GSE64392"
author: "Wei Zhang, Hanchen Huang, Xi S.Chen"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
    highlight: pygments
    theme: yeti
    toc: true
    number_sections: true
    df_print: paged
    code_download: true
    toc_float:
      collapsed: yes
    toc_depth: 3
editor_options:
  chunk_output_type: inline    
---

```{r setup, include=FALSE}
# Initial settings
knitr::opts_chunk$set(echo = TRUE)

dir.base <- "../../../"
# Create and retrieve dir
GEO <- "GSE64392"
dir.data <- file.path(dir.base, "data/", GEO)
dir.data.raw <- file.path(dir.data, "raw")
dir.data.processed <- file.path(dir.data, "processed")
dir.data.clinical <- file.path(dir.data, "clinical")

dir.results <- file.path(dir.base, "analysis-results/")
dir.results.corr <- file.path(dir.results, "corr/")
for(p in grep("dir",ls(),value = T)) dir.create(get(p),recursive = TRUE,showWarnings = FALSE)

```

# Auxillary function

```{r message = F}
fn_ls <- list.files("../utility/", pattern = ".R", full.names = T)
for (f in fn_ls) source(f)
```

# Data preprocessing

## Data download and get expression data

```{r eval = F}
# Gene expression profile of colorectal cancer tissues from 87 patients
GSE64392 <- getGEO(GEO = "GSE64392", destdir = dir.data.raw)
```

```{r}
# Get phenotype
pheno <- pData(GSE64392$GSE64392_series_matrix.txt.gz) %>%
  clean_names()

write_csv(
  pheno,
  file.path(dir.data.clinical, "COAD_GSE64392_organoids_clinical_data.csv")
)
```

## Expression data preprocessing

```{r}
# get organoid expression data
exp <- exprs(GSE64392$GSE64392_series_matrix.txt.gz)

#### use probe with largest IQR to represent the gene
arrayIQR <- apply(exp,1,IQR)
probe <- rownames(exp)
uniqueGenes <- findLargest(as.vector(probe),arrayIQR, 'hugene20sttranscriptcluster')

# annotation with gene symbol
exp2 <- exp[uniqueGenes,]
gene_symbol <- AnnotationDbi::select(hugene20sttranscriptcluster.db, 
                                     keys = uniqueGenes, 
                                     columns ="SYMBOL")
rownames(exp2) <- gene_symbol$SYMBOL
```

```{r}
# Save expression
write_csv(
  exp2 %>% data.frame() %>% rownames_to_column("Gene"),
  file.path(dir.data.processed, "COAD_GSE64392_org_exp_data.csv")
)
```

## Preprocessing drug response

```{r}
# Load drug response data from supplemental file
drug_res <- readxl::read_xlsx(
  file.path(dir.data.raw, "drug_response/1-s2.0-S0092867415003736-mmc3.xlsx"),
  sheet = 2
)
```

```{r}
# Use median value of IC50 as the drug response for each drug
drug_res_by_patient <- drug_res %>% 
  group_by(Organoid, Drug_ID, `Drug Name`) %>% 
  summarise(mIC50 = median(IC50),
            mAUC = median(AUC)) 

# Save drug response file
write_csv(
  drug_res_by_patient,
  file.path(dir.data.clinical, "COAD_GSE64392_drug_response_median_IC50.csv")
)
```

## Select Tumor samples

```{r}
pheno_CC <- pheno %>%
  filter(tissue_ch1 == "colon tumor") %>%
  mutate(Organoid = gsub("p","P",gsub("t", "", title)))

# Save clinical file
write_csv(
  pheno_CC,
  file.path(dir.data.clinical, "COAD_GSE64392_CC_clinical.csv")
)
```

```{r}
# Select tumor expression
exp_CC <- exp2[,pheno_CC$geo_accession]

# Save expression file
write_csv(
  exp_CC %>% data.frame() %>% rownames_to_column("Gene"),
  file.path(dir.data.processed, "COAD_GSE64392_org_CC_exp_data.csv")
)
```

```{r}
save(
  exp_CC,
  pheno_CC,
  drug_res_by_patient,
  file = file.path(dir.data.processed, "COAD_GSE64392_org_CC_with_drug_info_matched_exp_clinical_data.rda")
)
```

# Calculate gene-drug correlation

## Load GSE64392 drug response 

```{r}
# GSE64392 (exp_CC, clinical, drug_res_by_patient)
load(file = file.path(dir.data.processed,
                      "/COAD_GSE64392_org_CC_with_drug_info_matched_exp_clinical_data.rda"))
```

```{r}
# Load clinical and drug response for GSE64392
GSE64392c <- pheno_CC
GSE64392_drug <- drug_res_by_patient
GSE64392c <- left_join(drug_res_by_patient, GSE64392c)
```

```{r}
# Prepare drug response
GSE64392c_5fu <- GSE64392c %>% 
  filter(`Drug Name` == "5-Fluorouracil")

# prepare expression data
exp_GSE64392 <- exp_CC[, GSE64392c_5fu$geo_accession]
```

```{r}
# Calculate gene-drug correlation
corr_results <- corr_coef(exp_GSE64392,
                          GSE64392c_5fu,
                          drug_var = "mIC50",
                          parallel = F)
```

```{r}
corr_results$fdr <- p.adjust(corr_results$p.value, method = "fdr")
```

```{r eval = F}
# Save results
readr::write_csv(
  corr_results,
  file.path(dir.results.corr, "GSE64392_gene_drug_corr.csv")
)
```

```{r}
# Calculate gene-drug correlation
corr_results_sp <- corr_coef(exp_GSE64392,
                          GSE64392c_5fu,
                          drug_var = "mIC50",
                          parallel = F,
                          method = "spearman")
```

```{r}
corr_results_sp$fdr <- p.adjust(corr_results_sp$p.value, method = "fdr")
```

```{r eval = F}
# Save results
readr::write_csv(
  corr_results_sp,
  file.path(dir.results.corr, "GSE64392_gene_drug_sp_corr.csv")
)
```

# Session Information

```{r}
devtools::session_info()
```

